### ISSUE TITLE
Hide Icon

### ISSUE THREAD

**Issue by supersaiyansubtlety** [furybee/chrome-tab-modifier#124]
Browser: Chrome
Extension version: 0.21.0
Could you please add an option to hide a tab's icon in the list of included icons?

**Comment by sylouuu** [comment]
@clfer What do you think about that and would you be interested to make it?

Best

**Comment by clfer** [comment]
Hi

You can check branch [#124-Hide_icon](https://github.com/clfer/chrome-tab-modifier/tree/feature/%23124-Hide_icon)
I'm not fully satisfied... All it does is display an empty favicon

**Comment by sylouuu** [comment]
What about removing all icons?

A condition [here](https://github.com/sylouuu/chrome-tab-modifier/blob/master/src/js/content.js#L162) and return true ;)

**Comment by clfer** [comment]
I tried it at first but it doesn't work like this...

If there is no icon, the browser while try '/favicon.ico' and such (and most of the site I've tested have this fallback icon) 

Another naive attempt was an empty href for shortcut icon
```html
<link href="" rel="shortcut icon">
```

This doesn't work either as chrome display a default icon...

That's why i came up with this solution

**Comment by somethingSTRANGE** [comment]
If you want to just show an invisible icon, you can use a data URI to provide a transparent pixel, such as:
`data:image/gif;base64,R0lGODlhAQABAIAAAP///wAAACH5BAEAAAAALAAAAAABAAEAAAICRAEAOw==` provided by an [Online Transparent Pixel Generator](https://png-pixel.com/)

You can also hide the tab name by placing a [Zero Width Space](https://zerowidthspace.me/) character to override the title.
