### ISSUE TITLE
repeated renames do not work

### ISSUE THREAD

**Issue by sershe** [furybee/chrome-tab-modifier#140]
### Tab Modifier version

**Browser:** `Chrome`

**Extension version:** `0.22.0`

### Expected behavior

When "rename tab" is used multiple times on the same tab, the last name should stick.

### Actual behavior

The first title is the one used.

### Steps to reproduce the behavior

1. Rename tab to "tab1"
2. Rename tab to "tab2"
The tab refreshes and the name is still tab1... looks like renames should delete the conflicting rules for the same url

**Comment by sylouuu** [comment]
Hello,

Quoted from the Help page:

> The order of your rules is important, if an URL triggers more than one rule, the first one will be applied. You can reorder your rules anyway.

**Comment by orschiro** [comment]
Dear all, 

I think there is something here we can improve. 

If you rename a tab from the context menu option and then repeat this very same procedure, in my opinion, Tab Modifier should disregard the first renaming rule and only apply the second one. 

What do you think?

Yours,

Robert

**Comment by sylouuu** [comment]
I think the current behavior is OK, small extra logics are not necessary at this point.

Then you keep a total control of your rules and up to you to have duplicates. :)

"Take control of your tabs" 💪

Regards

**Comment by imageslr** [comment]
Hi @sylouuu , 

I think it's inconvenient since usually we will usually rename a tab two or three times. For example, if I have typo and I need to fix, I will rename the tab again through context menu. 

However, I have to click every tab rule in TabModifier since the name are all starting will "Rule created from right-click ..." and I can't search rule by url.

I think that keeping url unique in all ruleset is important, or having a button in TabModifier to remove all duplicated rule (this is more customizable and is compatible to older version).

Thanks.

**Comment by imageslr** [comment]
Hi @orschiro  @sershe , 

I have made a fork version to achieve the purpose.  See https://github.com/imageslr/chrome-tab-modifier .

Please try it!

Yours
